In [ ]:
import cv2
print cv2.__version__

In [ ]:
# Capture Video on Camera
# Shows video in gray scale in a new window
# Adapted from: http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
# Capture Video on Camera
# Shows video in gray scale in a new window
import numpy as np
import cv2

cap = cv2.VideoCapture()

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
# Calculates Frames Per Second of Video/Camera
# Adapted from: http://www.learnopencv.com/how-to-find-frame-rate-or-frames-per-second-fps-in-opencv-python-cpp/
import cv2
import time
 
# Start default camera
video = cv2.VideoCapture(0);

# Find OpenCV version
(major_ver, minor_ver, subminor_ver) = (cv2.__version__).split('.')

# With webcam get(CV_CAP_PROP_FPS) does not work.
# Let's see for ourselves.

if int(major_ver)  < 3 :
    fps = video.get(cv2.cv.CV_CAP_PROP_FPS)
    print "Frames per second using video.get(cv2.cv.CV_CAP_PROP_FPS): {0}".format(fps)
else :
    fps = video.get(cv2.CAP_PROP_FPS)
    print "Frames per second using video.get(cv2.CAP_PROP_FPS) : {0}".format(fps)


# Number of frames to capture
num_frames = 120;


print "Capturing {0} frames".format(num_frames)

# Start time
start = time.time()

# Grab a few frames
for i in xrange(0, num_frames) :
    ret, frame = video.read()
    cv2.imshow('frame', frame)


# End time
end = time.time()

# Time elapsed
seconds = end - start
print "Time taken : {0} seconds".format(seconds)

# Calculate frames per second
fps  = num_frames / seconds;
print "Estimated frames per second : {0}".format(fps);

# Release video
video.release()

In [ ]:
cv2.destroyAllWindows()

In [ ]:
# Capture Video on Camera
# Shows video in gray scale with face detection in a new window
# Adapted from: https://realpython.com/blog/python/face-recognition-with-python/
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
# Create the haar cascade
faceCascade = cv2.CascadeClassifier("/usr/local/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml")

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # Detect Face in frame
    faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30)
    )
    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(gray, (x, y), (x+w, y+h), (0, 255, 0), 2)


    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
# Capture Video on Camera
# Shows video in gray scale with face detection in a new window
# Adapted from: https://realpython.com/blog/python/face-recognition-with-python/
import numpy as np
import cv2
import dlib

cap = cv2.VideoCapture(0)
win = dlib.image_window()

# Create the haar cascade
faceCascade = cv2.CascadeClassifier("/usr/local/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml")

# Initialize variables for dLib
#predictor_path = "/Users/pybeebee/HS Science Fair/shape_predictor_68_face_landmarks.dat"
#detector = dlib.get_frontal_face_detector()
#predictor = dlib.shape_predictor(predictor_path)


while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Detect Face in frame
    faces = faceCascade.detectMultiScale(frame, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    
    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
    
    # Use dLib to locate and display facial landmarks
    #dets = detector(frame, 1)
    #for k, d in enumerate(dets):
        #shape = predictor(frame, d)
        #frame.add_overlay(shape)
    
    # Display the resulting frame
    #cv2.imshow('frame',frame) 
    win.clear_overlay()
    win.set_image(frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
# Show video in color
# Displays box around face
# Displays facial landmarks for each face

import cv2
import dlib

cap = cv2.VideoCapture(0)

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # Detect faces and initialize variables for next step
    dets = detector(frame, 1)
    x_list = list()
    y_list = list()
    
    # Get list of x-coordinates and y-coordinates of facial landmarks for each face
    for d in dets:
        shape = predictor(frame, d)
        for index in range(0, 68):
            point = shape.part(index)
            x_list.append(point.x)
            y_list.append(point.y)
    
    # Draw a rectangle around the faces
    for rect in dets:
        cv2.rectangle(frame, (rect.left(), rect.top()), (rect.right(), rect.bottom()), (0, 255, 0), 2)
    
    # Display facial landmark points on frame
    for i in range((len(dets)*68)):
        cv2.circle(frame, (x_list[i], y_list[i]), 3, (0, 0, 255), -1)
       
    # Display frame, press 'q' to exit video window
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
# Show video in color
# DOES NOT display box around face
# Displays facial landmarks for each face

import cv2
import dlib

cap = cv2.VideoCapture(0)

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # Detect faces and initialize variables for next step
    dets = detector(frame, 1)
    x_list = list()
    y_list = list()
    
    # Get list of x-coordinates and y-coordinates of facial landmarks for each face
    for d in dets:
        shape = predictor(frame, d)
        for index in range(0, 68):
            point = shape.part(index)
            x_list.append(point.x)
            y_list.append(point.y)
    
    # Display facial landmark points on frame
    for i in range((len(dets)*68)):
        cv2.circle(frame, (x_list[i], y_list[i]), 4, (0, 255, 0), -1)
       
    # Display frame, press 'q' to exit video window
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()

In [ ]:
# Show video in color
# DOES NOT display box around face
# Displays facial landmarks for each face, change display upon pressing 'n' or 'o' keys

import numpy as np
import cv2
import dlib

cap = cv2.VideoCapture(0)
state = 1

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    origFrame = frame.copy()
    
    # Detect faces and initialize variables for next step
    dets = detector(frame, 1)
    x_list = list()
    y_list = list()
    
    # Get list of x-coordinates and y-coordinates of facial landmarks for each face
    for d in dets:
        shape = predictor(frame, d)
        for index in range(0, 68):
            point = shape.part(index)
            x_list.append(point.x)
            y_list.append(point.y)
    
    # Display facial landmark points on frame
    for i in range((len(dets)*68)):
        cv2.circle(frame, (x_list[i], y_list[i]), 3, (0, 255, 0), -1)
       
    # Display frame, n = display with lm, o = display w/o lm, q = exit video window
    #cv2.imshow('frame',frame)
    key = cv2.waitKey(5)
    if key == ord('o'):
        state = 0
    elif key == ord('l'):
        state = 1
    elif key == ord('q'):
        break
        
    if state == 0:
        cv2.imshow('frame',origFrame)
    if state == 1:
        cv2.imshow('frame',frame)
        

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()

In [ ]:
# Classifies images in CK+ dataset to either neutral or expression category folders
import os

for root, dirs, files in os.walk("./cohn-kanade-images"):
    filelist=[]
    for name in files:
        filename = os.path.join(root, name)
        if '.png' in filename:
            filelist.append(filename)
    if len(filelist) > 0:
        neutralfile = filelist[0]
        !cp $neutralfile Neutral
        expressfile = filelist[-1]
        !cp $expressfile Expression
        print

In [ ]:
# Apply 68-point Facial Landmark Detection Model to CK+ Dataset, neutral faces
# DOES display box around face
# Displays facial landmarks for each face

import cv2
import dlib
import os

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

for root, dirs, files in os.walk("./Neutral"):
    for name in files:
        filename = os.path.join(root, name)

        # Read image if of correct type (8bit gray or RGB)
        if '.png' in filename:
            image = cv2.imread(filename, 1)

            # Detect faces and initialize variables for next step
            dets = detector(image, 1)
            x_list = list()
            y_list = list()

            # Get list of x-coordinates and y-coordinates of facial landmarks for each face
            for d in dets:
                shape = predictor(image, d)
                for index in range(0, 68):
                    point = shape.part(index)
                    x_list.append(point.x)
                    y_list.append(point.y)

            # Display rectangle around face
            for rect in dets:
                cv2.rectangle(image, (rect.left(), rect.top()), (rect.right(), rect.bottom()), (0, 255, 0), 2)
            
            # Display facial landmark points on frame
            for i in range((len(dets)*68)):
                cv2.circle(image, (x_list[i], y_list[i]), 3, (0, 255, 0), -1)

            # Display frame, 'q' to stop
            cv2.imshow('frame',image)
            key = cv2.waitKey(50)
            if key == ord('q'):
                break

# When everything is done, destroy the window
#cv2.destroyAllWindows()

In [ ]:
# Apply 68-point Facial Landmark Detection Model to CK+ Dataset, faces with expressions
# DOES display box around face
# Displays facial landmarks for each face

import cv2
import dlib
import os

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

for root, dirs, files in os.walk("./Expression"):
    for name in files:
        filename = os.path.join(root, name)

        # Read image if of correct type (8bit gray or RGB)
        if '.png' in filename:
            image = cv2.imread(filename, 1)

            # Detect faces and initialize variables for next step
            dets = detector(image, 1)
            x_list = list()
            y_list = list()

            # Get list of x-coordinates and y-coordinates of facial landmarks for each face
            for d in dets:
                shape = predictor(image, d)
                for index in range(0, 68):
                    point = shape.part(index)
                    x_list.append(point.x)
                    y_list.append(point.y)

            # Display rectangle around face
            for rect in dets:
                cv2.rectangle(image, (rect.left(), rect.top()), (rect.right(), rect.bottom()), (0, 255, 0), 2)
            
            # Display facial landmark points on frame
            for i in range((len(dets)*68)):
                cv2.circle(image, (x_list[i], y_list[i]), 3, (0, 255, 0), -1)

            # Display frame, 'q' to stop
            cv2.imshow('frame',image)
            key = cv2.waitKey(50)
            if key == ord('q'):
                break

# When everything is done, destroy the window
#cv2.destroyAllWindows()

In [ ]:
# OLD: get numpy array of expression and neutral differences for each image
import cv2
import dlib
import os
import numpy as np
import math

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)
# Initialize other variables
NLA = []
ELA = []
tempLDA = []
# Get landmarks for neutral images
for root, dirs, files in os.walk("./Neutral"):
    for name in files:
        filename = os.path.join(root, name)

        # Read image if of correct type (8bit gray or RGB)
        if '.png' in filename:
            image = cv2.imread(filename, 1)

            # Detect faces and initialize variables for next step
            dets = detector(image, 1)

            # Get list of x-coordinates and y-coordinates of facial landmarks for each face
            for d in dets:
                imageNA = []
                shape = predictor(image, d)
                for index in range(0, 68):
                    point = shape.part(index)
                    tuplepoint = (point.x, point.y)
                    imageNA.append(tuplepoint)
                NLA.append(imageNA)
                
# Get landmarks for expression images
for root, dirs, files in os.walk("./Expression"):
    for name in files:
        filename = os.path.join(root, name)

        # Read image if of correct type (8bit gray or RGB)
        if '.png' in filename:
            image = cv2.imread(filename, 1)

            # Detect faces and initialize variables for next step
            dets = detector(image, 1)

            # Get list of x-coordinates and y-coordinates of facial landmarks for each face
            for d in dets:
                imageEA = []
                shape = predictor(image, d)
                for index in range(0, 68):
                    point = shape.part(index)
                    tuplepoint = (point.x, point.y)
                    imageEA.append(tuplepoint)
                ELA.append(imageEA)

# Get list of Euclidean differences for each landmark point for each image, convert list to numpy.arrray, add to big list
for img in range(len(NLA)):
    tempImgLDA = []
    for point in range(68):
        dif = math.sqrt((math.pow(ELA[img][point][0]-NLA[img][point][0], 2)) + (math.pow(ELA[img][point][1]-NLA[img][point][1], 2)))
        tempImgLDA.append(dif)
    imgLDA = np.asarray(tempImgLDA)
    tempLDA.append(imgLDA)

# Convert big list of all differences for all images to numpy.array
LDA = np.asarray(tempLDA)

# Subtract the average from the LDA values to see if there is any change
for img in range(len(LDA)):
    sum = 0
    for valueIndex in range(len(LDA[img])):
        sum+=LDA[img][valueIndex]
    average = sum/68
    for vI in range(len(LDA[img])):
        LDA[img][vI]-=average

In [1]:
# DRAFT
# Create 327x3 matrix, for each image set contains neutral image name, expression image name, emotion label
# Generate normalized Euclidean Differences array
# Generate target values array
# Feed to SVM, evaulate with Cross Validation
import cv2
import dlib
import os
import math

# Function that returns array of 68 landmarks for given image name
def get68LMA(imgName):
    predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(predictor_path)
    LMA = []
    image = cv2.imread(imgName, 1)
    
    # Detect face(s)
    dets = detector(image, 1)

    # Get list of coordinates of 68 facial landmarks for each face
    for d in dets:
        shape = predictor(image, d)
        for index in range(0, 68):
            point = shape.part(index)
            tuplepoint = (point.x, point.y)
            LMA.append(tuplepoint)
    return LMA

# Function that eturns normalized array of Euclidean distances given two arrays of coordinates
def getEucDist(nLA, eLA):
    LDA = []
    sum = 0
    # Get array of distances
    for pt in range(68):
        x1 = eLA[pt][0]
        x2 = nLA[pt][0]
        y1 = eLA[pt][1]
        y2 = nLA[pt][1]
        dif = math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2))     
        LDA.append(dif)
        sum += dif
    avg = sum/68
    # Normalize array
    for i in range(68):
        LDA[i] -= avg
        
    return LDA


# Get paths to face images and emotion labels
imagedir = []
labeldir = []
root, dirs, files = os.walk("./cohn-kanade-images",).next()
for d in dirs:
    imagedir.append(os.path.join(root,d))
    labeldir.append(os.path.join('./Emotion',d))

# initialize datset
dataset = []

# look over all directories of individuals S001 through S999
for d in dirs:
    for dd in os.listdir(os.path.join('./cohn-kanade-images',d)):
        # skip over .DS_Store files
        if 'Store' not in dd:
            curdir = os.path.join('./cohn-kanade-images',d,dd)
            files = os.listdir(curdir)
            baseimage = os.path.join(curdir,files[0])
            faceimage = os.path.join(curdir,files[-1])

            # get directories of multiple expressions of same person
            labeldir = os.path.join('./Emotion',d,dd)
            if os.path.isdir(labeldir):
                labels = os.listdir(labeldir)
                # read label file if it exists
                if len(labels)>0:
                    f=open(os.path.join(labeldir,labels[0]),"r")
                    for line in f:
                        targetlabel = float(line)
                    f.close()
                    
                    # append label to dataset
                    dataset.append([baseimage, faceimage, targetlabel])

# Get array of Euclidean differences between neutral and expression 68-landmark arrays
LDA = []
for imgIndex in range(len(dataset)):
    nImgName = dataset[imgIndex][0]
    eImgName = dataset[imgIndex][1]
    nLA = get68LMA(nImgName)
    eLA = get68LMA(eImgName)
    LDA.append(getEucDist(nLA, eLA))

# Create target value array for expression images
targetValues = []
for imgSet in range(len(dataset)):
    targetValues.append(dataset[imgSet][2])

In [3]:
# DRAFT
import numpy as np
realLDA = np.asmatrix(LDA)
np.savetxt('LDAfile', realLDA)

In [4]:
# DRAFT
realTargetValues = np.asarray(targetValues)
np.savetxt('targetValuesFile', realTargetValues)

In [15]:
# OLD: use cross validation
from sklearn import svm
from sklearn import cross_validation
clf = svm.SVC(kernel='linear').fit(realLDA, realTargetValues)
scores = cross_validation.cross_val_score(clf, realLDA, realTargetValues, cv=4)
print scores


[ 0.70588235  0.70731707  0.69135802  0.70886076]


In [34]:
# Calculate confusion matrix for base model with SVM and Cross Validation
# Convert confusion matrix to contain percentages 
from sklearn.metrics import confusion_matrix

x_train, x_test, y_train, y_test = cross_validation.train_test_split(realLDA, realTargetValues, test_size=0.4, random_state=2)
clf2 = svm.SVC(kernel='linear').fit(x_train, y_train)
predictions = clf2.predict(x_test)
cmatrix = confusion_matrix(y_test, predictions)

# Format CMatrix to have percentages
np.set_printoptions(precision=1)
rowSums = np.sum(cmatrix, axis=1)
pCMatrix = np.divide(cmatrix*100., np.sum(cmatrix, axis=1), dtype=float)
print pCMatrix

[[ 60.    0.   15.8  15.4   0.   25.    3.2]
 [  0.   62.5   5.3   0.    3.1  12.5   0. ]
 [ 20.   12.5  57.9  15.4   0.   12.5   0. ]
 [ 15.    0.   15.8  38.5   3.1  12.5   0. ]
 [  0.    0.   10.5   7.7  90.6   0.    0. ]
 [  5.   25.    0.    0.    3.1  50.    0. ]
 [ 15.    0.    0.   23.1   0.    0.   80.6]]


In [2]:
# WORKING VERSION OF COMBINED DRAFTS
# Create 327x3 matrix, for each image set contains neutral image name, expression image name, emotion label
# Generate normalized Euclidean Differences array
# Generate target values array
# Feed to SVM, evaulate with Cross Validation
import numpy as np
import cv2
import dlib
import os
import math
from sklearn import svm
from sklearn import cross_validation
from sklearn.metrics import confusion_matrix

# Function that returns array of 68 landmarks for given image name
def get68LMA(imgName):
    predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(predictor_path)
    LMA = []
    image = cv2.imread(imgName, 1)
    
    # Detect face(s)
    dets = detector(image, 1)

    # Get list of coordinates of 68 facial landmarks for each face
    for d in dets:
        shape = predictor(image, d)
        for index in range(0, 68):
            point = shape.part(index)
            tuplepoint = (point.x, point.y)
            LMA.append(tuplepoint)
    return LMA

# Function that eturns normalized array of Euclidean distances given two arrays of coordinates
def getEucDist(nLA, eLA):
    LDA = []
    sum = 0
    # Get array of distances
    for pt in range(68):
        x1 = eLA[pt][0]
        x2 = nLA[pt][0]
        y1 = eLA[pt][1]
        y2 = nLA[pt][1]
        dif = math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2))     
        LDA.append(dif)
        sum += dif
    avg = sum/68
    # Normalize array
    for i in range(68):
        LDA[i] -= avg
        
    return LDA

# Get paths to face images and emotion labels
imagedir = []
labeldir = []
root, dirs, files = os.walk("./cohn-kanade-images",).next()
for d in dirs:
    imagedir.append(os.path.join(root,d))
    labeldir.append(os.path.join('./Emotion',d))

# initialize datset
dataset = []

# look over all directories of individuals S001 through S999
for d in dirs:
    for dd in os.listdir(os.path.join('./cohn-kanade-images',d)):
        # skip over .DS_Store files
        if 'Store' not in dd:
            curdir = os.path.join('./cohn-kanade-images',d,dd)
            files = os.listdir(curdir)
            baseimage = os.path.join(curdir,files[0])
            faceimage = os.path.join(curdir,files[-1])

            # get directories of multiple expressions of same person
            labeldir = os.path.join('./Emotion',d,dd)
            if os.path.isdir(labeldir):
                labels = os.listdir(labeldir)
                # read label file if it exists
                if len(labels)>0:
                    f=open(os.path.join(labeldir,labels[0]),"r")
                    for line in f:
                        targetlabel = float(line)
                    f.close()
                    
                    # append label to dataset
                    dataset.append([baseimage, faceimage, targetlabel])

# Get array of Euclidean differences between neutral and expression 68-landmark arrays
tempLDA = []
for imgIndex in range(len(dataset)):
    nImgName = dataset[imgIndex][0]
    eImgName = dataset[imgIndex][1]
    nLA = get68LMA(nImgName)
    eLA = get68LMA(eImgName)
    tempLDA.append(getEucDist(nLA, eLA))
LDA = np.asmatrix(tempLDA)

# Create target value array for expression images
tempTargetValues = []
for imgSet in range(len(dataset)):
    tempTargetValues.append(dataset[imgSet][2])
targetValues = np.asarray(tempTargetValues)

# Feed LDA and targetValues int SVM, use cross validation, generate confusion matrix
x_train, x_test, y_train, y_test = cross_validation.train_test_split(LDA, targetValues, test_size=0.4, random_state=2)
clf = svm.SVC(kernel='linear').fit(x_train, y_train)
predictions = clf.predict(x_test)
cmatrix = confusion_matrix(y_test, predictions)

# Format CMatrix to show percentages, rounded to 1 decimal point
np.set_printoptions(precision=1)
rowSums = np.sum(cmatrix, axis=1)
pCMatrix = np.divide(cmatrix*100., np.sum(cmatrix, axis=1), dtype=float)
print pCMatrix

[[ 60.    0.   15.8  15.4   0.   25.    3.2]
 [  0.   62.5   5.3   0.    3.1  12.5   0. ]
 [ 20.   12.5  57.9  15.4   0.   12.5   0. ]
 [ 15.    0.   15.8  38.5   3.1  12.5   0. ]
 [  0.    0.   10.5   7.7  90.6   0.    0. ]
 [  5.   25.    0.    0.    3.1  50.    0. ]
 [ 15.    0.    0.   23.1   0.    0.   80.6]]


In [21]:
# WORKING VERSION OF COMBINED DRAFTS
# Create 327x3 matrix, for each image set contains neutral image name, expression image name, emotion label
# Generate normalized Euclidean Differences array
# Generate target values array
# Feed to SVM, evaulate with Cross Validation
import numpy as np
import cv2
import dlib
import os
import math
from sklearn import svm
from sklearn import cross_validation
from sklearn.metrics import confusion_matrix

# Function that returns the distance between two given points
def ptDist(pt1, pt2):
    x1 = pt1[0]
    x2 = pt2[0]
    y1 = pt1[1]
    y2 = pt2[1]
    return math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2))

# Function that returns array of 68 landmarks for given image name
def get68LMA(imgName):
    predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(predictor_path)
    LMA = []
    image = cv2.imread(imgName, 1)
    
    # Detect face(s)
    dets = detector(image, 1)

    # Get list of coordinates of 68 facial landmarks for each face
    for d in dets:
        shape = predictor(image, d)
        for index in range(0, 68):
            point = shape.part(index)
            tuplepoint = (point.x, point.y)
            LMA.append(tuplepoint)
    return LMA

# Function that eturns normalized array of Euclidean distances given two arrays of coordinates
def getEucDist(nLA, eLA):
    LDA = []
    sum = 0
    # Get array of distances
    for pt in range(68):
        dif = ptDist(eLA[pt], nLA[pt])     
        LDA.append(dif)
        sum += dif
    avg = sum/68
    # Normalize array
    for i in range(68):
        LDA[i] -= avg      
    return LDA

# Function that returns 13-point numpy vector of distances between selected physiological pts, given the 68-point vector
def getPDA(iLA):
    PDA = []
    PDA.append(ptDist(iLA[20], iLA[21])) #distance 0: distance between brows
    PDA.append(ptDist(iLA[20], iLA[26])) #distance 1: inner brow to nose- left
    PDA.append(ptDist(iLA[21], iLA[26])) #distance 2: inner brow to nose- right
    PDA.append(ptDist(iLA[20], iLA[38])) #distance 3: inner brow to inner eye corner- left
    PDA.append(ptDist(iLA[21], iLA[41])) #distance 4: inner brow to inner eye corner- right
    PDA.append(ptDist(iLA[35], iLA[47])) #distance 5: outer eye corner to outer mouth corner- left
    PDA.append(ptDist(iLA[44], iLA[53])) #distance 6: outer eye corner to outer mouth corner- right
    PDA.append(ptDist(iLA[47], iLA[53])) #distance 7: distance between mouth corners
    PDA.append(ptDist(iLA[61], iLA[65])) #distance 8: height of mouth
    PDA.append(ptDist(iLA[35], iLA[49])) #distance 9: raising of upper lip
    PDA.append(ptDist(iLA[44], iLA[51])) #distance 10: raising of upper lip
    PDA.append(ptDist(iLA[18], iLA[36])) #distance 11: brow arch- left
    PDA.append(ptDist(iLA[23], iLA[43])) #distance 12: brow arch- right
    return np.asarray(PDA)

"""MAIN PROGRAM BEGINS"""
# Get paths to face images and emotion labels
imagedir = []
labeldir = []
root, dirs, files = os.walk("./cohn-kanade-images",).next()
for d in dirs:
    imagedir.append(os.path.join(root,d))
    labeldir.append(os.path.join('./Emotion',d))

# initialize variables
dataset = []
NLA = []
ELA = []

# look over all directories of individuals S001 through S999
for d in dirs:
    for dd in os.listdir(os.path.join('./cohn-kanade-images',d)):
        # skip over .DS_Store files
        if 'Store' not in dd:
            curdir = os.path.join('./cohn-kanade-images',d,dd)
            files = os.listdir(curdir)
            baseimage = os.path.join(curdir,files[0])
            faceimage = os.path.join(curdir,files[-1])

            # get directories of multiple expressions of same person
            labeldir = os.path.join('./Emotion',d,dd)
            if os.path.isdir(labeldir):
                labels = os.listdir(labeldir)
                # read label file if it exists
                if len(labels)>0:
                    f=open(os.path.join(labeldir,labels[0]),"r")
                    for line in f:
                        targetlabel = float(line)
                    f.close()
                    
                    # append label to dataset
                    dataset.append([baseimage, faceimage, targetlabel])

"""68-POINT LANDMARK DETECTION MODEL"""
# Get array of Euclidean differences between neutral and expression 68-landmark arrays
tempLDA = []
for imgIndex in range(len(dataset)):
    nImgName = dataset[imgIndex][0]
    eImgName = dataset[imgIndex][1]
    nLA = get68LMA(nImgName)
    eLA = get68LMA(eImgName)
    NLA.append(nLA)
    ELA.append(eLA)
    tempLDA.append(getEucDist(nLA, eLA))
LDA = np.asmatrix(tempLDA)

# Create target value array for expression images
tempTargetValues = []
for imgSet in range(len(dataset)):
    tempTargetValues.append(dataset[imgSet][2])
targetValues = np.asarray(tempTargetValues)

# Feed LDA and targetValues into SVM, use cross validation, generate confusion matrix
x_train, x_test, y_train, y_test = cross_validation.train_test_split(LDA, targetValues, test_size=0.4, random_state=2)
normCLF = svm.SVC(kernel='linear').fit(x_train, y_train)
predictions = normCLF.predict(x_test)
cmatrix = confusion_matrix(y_test, predictions)

# Format CMatrix to show percentages, rounded to 1 decimal point
np.set_printoptions(precision=1)
rowSums = np.sum(cmatrix, axis=1)
pCMatrix = np.divide(cmatrix*100., rowSums, dtype=float)
print pCMatrix


"""PHYSIOLOGICALLY BASED LANDMARK DETECTION MODEL"""
# Get array of corresponding differences between 13 distances of base images and expression images
tempPDA = []
for i in range(len(NLA)):
    tempPDA.append(getPDA(NLA[i])-getPDA(ELA[i]))
PDA = np.asmatrix(tempPDA)
np.savetxt('PDAfile', PDA) #Save PDA as human-readable format file

# Feed PDA and targetValues into SVM, use cross validation, generate confusion matrix
x_train2, x_test2, y_train2, y_test2 = cross_validation.train_test_split(PDA, targetValues, test_size=0.4, random_state=3)
physCLF = svm.SVC(kernel='linear').fit(x_train2, y_train2)
predictions2 = physCLF.predict(x_test2)
cMatrix2 = confusion_matrix(y_test2, predictions2)

# Format CMatrix2 to show percentages, already rounded to 1 decimal point
rowSums2 = np.sum(cMatrix2, axis=1)
pCMatrix2 = np.divide(cMatrix2*100., rowSums2, dtype=float)
print pCMatrix2

[[ 60.    0.   15.8  15.4   0.   25.    3.2]
 [  0.   62.5   5.3   0.    3.1  12.5   0. ]
 [ 20.   12.5  57.9  15.4   0.   12.5   0. ]
 [ 15.    0.   15.8  38.5   3.1  12.5   0. ]
 [  0.    0.   10.5   7.7  90.6   0.    0. ]
 [  5.   25.    0.    0.    3.1  50.    0. ]
 [ 15.    0.    0.   23.1   0.    0.   80.6]]
[[ 73.3  28.6  10.    0.    0.    0.    0. ]
 [  6.7  85.7   0.    0.    0.    0.    0. ]
 [  6.7  14.3  90.    0.    0.    0.    0. ]
 [  6.7   0.    0.   63.6   3.6  13.3   0. ]
 [  0.    0.    5.    0.   96.4   0.    0. ]
 [ 33.3   0.    0.   27.3   0.   40.    2.9]
 [  0.   14.3   0.    9.1   0.    6.7  91.4]]


In [25]:
np.set_printoptions(precision=3)
normModelScores = cross_validation.cross_val_score(normCLF, LDA, targetValues, cv=4)
physModelScores = cross_validation.cross_val_score(normCLF, PDA, targetValues, cv=4)
print np.average(normModelScores)
print np.average(physModelScores)

0.703354552574
0.840391634453


In [32]:
x_train3, x_test3, y_train3, y_test3 = cross_validation.train_test_split(PDA, targetValues, test_size=0.4, random_state=2)
physCLF = svm.SVC(kernel='linear').fit(x_train3, y_train3)
predictions3 = physCLF.predict(x_test3)
cMatrix3 = confusion_matrix(y_test3, predictions3)
print cMatrix3
# Format CMatrix2 to show percentages, already rounded to 1 decimal point
rowSums3 = np.sum(cMatrix3, axis=1)
pCMatrix3 = np.divide(cMatrix2*100., np.sum(cMatrix3, axis=1), dtype=float)
print pCMatrix3
print rowSums3
print 28./31.

[[15  0  4  0  0  1  0]
 [ 0  7  0  0  0  1  0]
 [ 0  0 19  0  0  0  0]
 [ 1  1  0  8  1  2  0]
 [ 0  0  0  0 32  0  0]
 [ 1  1  1  0  0  4  1]
 [ 0  0  0  2  0  1 28]]
[[  55.      25.      10.526    0.       0.       0.       0.   ]
 [   5.      75.       0.       0.       0.       0.       0.   ]
 [   5.      12.5     94.737    0.       0.       0.       0.   ]
 [   5.       0.       0.      53.846    3.125   25.       0.   ]
 [   0.       0.       5.263    0.      84.375    0.       0.   ]
 [  25.       0.       0.      23.077    0.      75.       3.226]
 [   0.      12.5      0.       7.692    0.      12.5    103.226]]
[20  8 19 13 32  8 31]
0.903225806452


In [ ]:
# Show video in color
# Displays box around face
# Displays facial landmarks for each face

import cv2
import dlib

# Initialize variables for dLib
predictor_path = "/Users/kaililiu/HS Science Fair/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

while(True):
    # Capture frame-by-frame
    image = cv2.imread('',1)
    
    # Detect faces and initialize variables for next step
    dets = detector(image, 1)
    x_list = list()
    y_list = list()
    
    # Get list of x-coordinates and y-coordinates of facial landmarks for each face
    for d in dets:
        shape = predictor(frame, d)
        for index in range(0, 68):
            point = shape.part(index)
            x_list.append(point.x)
            y_list.append(point.y)
    
    # Draw a rectangle around the faces
    for rect in dets:
        cv2.rectangle(frame, (rect.left(), rect.top()), (rect.right(), rect.bottom()), (0, 255, 0), 2)
    
    # Display facial landmark points on frame
    for i in range((len(dets)*68)):
        cv2.circle(frame, (x_list[i], y_list[i]), 3, (0, 0, 255), -1)
       
    # Display frame, press 'q' to exit video window
    cv2.imshow('frame',image)

# When everything done, release the capture
cv2.destroyAllWindows()